# Generated by Django 4.1.7 on 2026-07-18 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('ready', 'Ready'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='invited', max_length=10)),
                ('car', models.CharField(blank=True, max_length=50, null=True)),
                ('reward', models.IntegerField(default=0)),
                ('exp_reward', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_missions', to='cities.city')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions_driven', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ooe_extraction_missions',
            },
        ),
        migrations.AddIndex(
            model_name='extractionmission',
            index=models.Index(fields=['initiator', 'status'], name='ooe_extract_initiat_4ffb72_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionmission',
            index=models.Index(fields=['driver', 'status'], name='ooe_extract_driver__263900_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionmission',
            index=models.Index(fields=['status', 'created_at'], name='ooe_extract_status_98ee36_idx'),
        ),
    ]
