# Generated by Django 4.1.7 on 2023-10-31 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGroup',
            new_name='ChatRoom',
        ),
        migrations.RenameField(
            model_name='chatconnection',
            old_name='chat_group',
            new_name='chat_room',
        ),
        migrations.AlterModelTable(
            name='chatroom',
            table='ooe_chat_rooms',
        ),
    ]
