# Generated by Django 4.1.7 on 2025-05-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money_cash', models.IntegerField(default=0)),
                ('money_bank', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=1)),
                ('attack_points', models.IntegerField(default=0)),
                ('defense_points', models.IntegerField(default=0)),
                ('driving_points', models.IntegerField(default=0)),
                ('commendations', models.IntegerField(default=0)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
            options={
                'db_table': 'ooe_users',
            },
        ),
    ]
