# Generated by Django 4.1.7 on 2026-07-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commendations',
        ),
    ]
