# Generated by Django 4.1.7 on 2023-10-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='money_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='money_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
