# Generated by Django 4.1.7 on 2023-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_exp_user_rank_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money_bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='money_cash',
            field=models.IntegerField(default=0),
        ),
    ]
