# Generated by Django 4.1.7 on 2026-07-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_commendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
