# Generated by Django 4.1.7 on 2023-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_money_bank_alter_user_money_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attack_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='defense_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_points',
            field=models.IntegerField(default=0),
        ),
    ]
