# Generated by Django 4.1.7 on 2023-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_attack_points_user_defense_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commendations',
            field=models.IntegerField(default=0),
        ),
    ]
