# Generated by Django 4.1.7 on 2025-05-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ooe_cities',
            },
        ),
        migrations.CreateModel(
            name='CityRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travel_time_minutes', models.IntegerField()),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='cities.city')),
                ('original_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='cities.city')),
            ],
            options={
                'db_table': 'ooe_city_routes',
            },
        ),
    ]
