# Generated by Django 4.1.7 on 2026-07-07 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDrugState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_type', models.CharField(max_length=20)),
                ('precursor_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('intermediate_1_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('intermediate_2_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('intermediate_3_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('pending_money', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_tick_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_states', to='cities.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ooe_player_drug_state',
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='cities.city')),
            ],
            options={
                'db_table': 'ooe_sale_records',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('trained_at', models.DateTimeField()),
                ('is_trained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_drug_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='black_market.playerdrugstate')),
            ],
            options={
                'db_table': 'ooe_professionals',
            },
        ),
        migrations.CreateModel(
            name='DrugPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_prices', to='cities.city')),
            ],
            options={
                'db_table': 'ooe_drug_prices',
            },
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['city', 'drug_type', 'recorded_at'], name='ooe_sale_re_city_id_097c46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerdrugstate',
            unique_together={('user', 'drug_type', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='drugprice',
            unique_together={('city', 'drug_type')},
        ),
    ]
