# Generated by Django 4.1.7 on 2026-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdrugstate',
            name='pending_money',
        ),
        migrations.AddField(
            model_name='playerdrugstate',
            name='stash_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
