# Generated by Django 4.1.7 on 2026-07-14 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_usergun_delete_userweapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAirplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ooe_users_airplanes',
            },
        ),
    ]
